version: '3.5'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - training
  backend:
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - training 
    volumes:
      - model:/src/model
  training:
    build: ./training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
volumes:
  model:
  imgs:
  data:
