version: '3.5'

services:
    frontend:
        image: webfront
        ports: 
            - 5000:5000
    backend:
        image: webback
        restart: unless-stopped
        ports:
            - 8000:8000
        environment:
            - REDIS=localhost
        networks:
            - redis
    redis:
        image: redis
        networks: 
            - redis
networks:
    redis:
        driver: bridge

